<?php

return [
    'countries' => [
        'US' => [
            'name' => 'United States',
            'states' => [
                'AL' => 'Alabama',
                'AK' => 'Alaska',
                'AZ' => 'Arizona',
                'AR' => 'Arkansas',
                'CA' => 'California',
                'CO' => 'Colorado',
                'CT' => 'Connecticut',
                'DE' => 'Delaware',
                'FL' => 'Florida',
                'GA' => 'Georgia',
                'HI' => 'Hawaii',
                'ID' => 'Idaho',
                'IL' => 'Illinois',
                'IN' => 'Indiana',
                'IA' => 'Iowa',
                'KS' => 'Kansas',
                'KY' => 'Kentucky',
                'LA' => 'Louisiana',
                'ME' => 'Maine',
                'MD' => 'Maryland',
                'MA' => 'Massachusetts',
                'MI' => 'Michigan',
                'MN' => 'Minnesota',
                'MS' => 'Mississippi',
                'MO' => 'Missouri',
                'MT' => 'Montana',
                'NE' => 'Nebraska',
                'NV' => 'Nevada',
                'NH' => 'New Hampshire',
                'NJ' => 'New Jersey',
                'NM' => 'New Mexico',
                'NY' => 'New York',
                'NC' => 'North Carolina',
                'ND' => 'North Dakota',
                'OH' => 'Ohio',
                'OK' => 'Oklahoma',
                'OR' => 'Oregon',
                'PA' => 'Pennsylvania',
                'RI' => 'Rhode Island',
                'SC' => 'South Carolina',
                'SD' => 'South Dakota',
                'TN' => 'Tennessee',
                'TX' => 'Texas',
                'UT' => 'Utah',
                'VT' => 'Vermont',
                'VA' => 'Virginia',
                'WA' => 'Washington',
                'WV' => 'West Virginia',
                'WI' => 'Wisconsin',
                'WY' => 'Wyoming',
                'DC' => 'District of Columbia',
            ]
        ],
        'NG' => [
            'name' => 'Nigeria',
            'states' => [
                'AB' => 'Abia',
                'FC' => 'Abuja Federal Capital Territory',
                'AD' => 'Adamawa',
                'AK' => 'Akwa Ibom',
                'AN' => 'Anambra',
                'BA' => 'Bauchi',
                'BY' => 'Bayelsa',
                'BE' => 'Benue',
                'BO' => 'Borno',
                'CR' => 'Cross River',
                'DE' => 'Delta',
                'EB' => 'Ebonyi',
                'ED' => 'Edo',
                'EK' => 'Ekiti',
                'EN' => 'Enugu',
                'GO' => 'Gombe',
                'IM' => 'Imo',
                'JI' => 'Jigawa',
                'KD' => 'Kaduna',
                'KN' => 'Kano',
                'KT' => 'Katsina',
                'KE' => 'Kebbi',
                'KO' => 'Kogi',
                'KW' => 'Kwara',
                'LA' => 'Lagos',
                'NA' => 'Nasarawa',
                'NI' => 'Niger',
                'OG' => 'Ogun',
                'ON' => 'Ondo',
                'OS' => 'Osun',
                'OY' => 'Oyo',
                'PL' => 'Plateau',
                'RI' => 'Rivers',
                'SO' => 'Sokoto',
                'TA' => 'Taraba',
                'YO' => 'Yobe',
                'ZA' => 'Zamfara',
            ]
        ],
        'GB' => [
            'name' => 'United Kingdom',
            'states' => [
                'ENG' => 'England',
                'SCT' => 'Scotland',
                'WLS' => 'Wales',
                'NIR' => 'Northern Ireland',
            ]
        ],
        'CA' => [
            'name' => 'Canada',
            'states' => [
                'AB' => 'Alberta',
                'BC' => 'British Columbia',
                'MB' => 'Manitoba',
                'NB' => 'New Brunswick',
                'NL' => 'Newfoundland and Labrador',
                'NS' => 'Nova Scotia',
                'ON' => 'Ontario',
                'PE' => 'Prince Edward Island',
                'QC' => 'Quebec',
                'SK' => 'Saskatchewan',
                'NT' => 'Northwest Territories',
                'NU' => 'Nunavut',
                'YT' => 'Yukon',
            ]
        ],
        'AU' => [
            'name' => 'Australia',
            'states' => [
                'NSW' => 'New South Wales',
                'VIC' => 'Victoria',
                'QLD' => 'Queensland',
                'WA' => 'Western Australia',
                'SA' => 'South Australia',
                'TAS' => 'Tasmania',
                'ACT' => 'Australian Capital Territory',
                'NT' => 'Northern Territory',
            ]
        ],
        'IN' => [
            'name' => 'India',
            'states' => [
                'AN' => 'Andaman and Nicobar Islands',
                'AP' => 'Andhra Pradesh',
                'AR' => 'Arunachal Pradesh',
                'AS' => 'Assam',
                'BR' => 'Bihar',
                'CH' => 'Chandigarh',
                'CT' => 'Chhattisgarh',
                'DD' => 'Dadra and Nagar Haveli',
                'DM' => 'Daman and Diu',
                'DL' => 'Delhi',
                'GA' => 'Goa',
                'GJ' => 'Gujarat',
                'HR' => 'Haryana',
                'HP' => 'Himachal Pradesh',
                'JK' => 'Jammu and Kashmir',
                'JH' => 'Jharkhand',
                'KA' => 'Karnataka',
                'KL' => 'Kerala',
                'LD' => 'Lakshadweep',
                'MP' => 'Madhya Pradesh',
                'MH' => 'Maharashtra',
                'MN' => 'Manipur',
                'ML' => 'Meghalaya',
                'MZ' => 'Mizoram',
                'NL' => 'Nagaland',
                'OR' => 'Odisha',
                'PY' => 'Puducherry',
                'PB' => 'Punjab',
                'RJ' => 'Rajasthan',
                'SK' => 'Sikkim',
                'TN' => 'Tamil Nadu',
                'TG' => 'Telangana',
                'TR' => 'Tripura',
                'UP' => 'Uttar Pradesh',
                'UT' => 'Uttarakhand',
                'WB' => 'West Bengal',
            ]
        ],
        'GH' => [
            'name' => 'Ghana',
            'states' => [
                'AH' => 'Ashanti',
                'BA' => 'Brong-Ahafo',
                'CE' => 'Central',
                'EA' => 'Eastern',
                'GA' => 'Greater Accra',
                'NO' => 'Northern',
                'UE' => 'Upper East',
                'UW' => 'Upper West',
                'VO' => 'Volta',
                'WE' => 'Western',
            ]
        ],
        'KE' => [
            'name' => 'Kenya',
            'states' => [
                'CE' => 'Central',
                'CO' => 'Coast',
                'EA' => 'Eastern',
                'NA' => 'Nairobi Area',
                'NE' => 'North Eastern',
                'NY' => 'Nyanza',
                'RV' => 'Rift Valley',
                'WE' => 'Western',
            ]
        ],
        'ZA' => [
            'name' => 'South Africa',
            'states' => [
                'EC' => 'Eastern Cape',
                'FS' => 'Free State',
                'GP' => 'Gauteng',
                'KZN' => 'KwaZulu-Natal',
                'LP' => 'Limpopo',
                'MP' => 'Mpumalanga',
                'NC' => 'Northern Cape',
                'NW' => 'North West',
                'WC' => 'Western Cape',
            ]
        ],
        // Countries without states/provinces
        'BR' => ['name' => 'Brazil', 'states' => []],
        'CN' => ['name' => 'China', 'states' => []],
        'FR' => ['name' => 'France', 'states' => []],
        'DE' => ['name' => 'Germany', 'states' => []],
        'JP' => ['name' => 'Japan', 'states' => []],
        'EG' => ['name' => 'Egypt', 'states' => []],
        'MA' => ['name' => 'Morocco', 'states' => []],
        'TZ' => ['name' => 'Tanzania', 'states' => []],
        'UG' => ['name' => 'Uganda', 'states' => []],
        'ET' => ['name' => 'Ethiopia', 'states' => []],
    ]
];